name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
    REGION: asia-southeast-2
    GAR_LOCATION: asia-southeast2-docker.pkg.dev
    PROJECT_ID: psoyey
    REPOSITORY_NAME: library

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      - name: Auth to GCP
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }} --quiet 

      - name: Build Docker image
        run: |
          export IMAGE_NAME=${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID}}/${{ env.REPOSITORY_NAME }}/library:${{ steps.vars.outputs.sha_short }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          export IMAGE_NAME=${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID}}/${{ env.REPOSITORY_NAME }}/library:${{ steps.vars.outputs.sha_short }}
          gcloud run deploy $IMAGE_NAME \
            --image $IMAGE_NAME \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated