name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env: 
    IMAGE_NAME: library
    REGION: asia-southeast-2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Auth to GCP
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          export IMAGE_NAME=asia-southeast2-docker.pkg.dev/psoyey/library/library:$GITHUB_SHA
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          export IMAGE_NAME=asia-southeast2-docker.pkg.dev/psoyey/library/library:$GITHUB_SHA
          gcloud run deploy $IMAGE_NAME \
            --image $IMAGE_NAME \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated